### ISSUE TITLE
Support refresh menus

### ISSUE THREAD

**Issue by hinerm** [imagej/ij1-patcher#31]
This is a useful function of ImageJ and it is unfortunate that we have had to drop its support to perform class modification magic.

It would be nice to restore this functionality.

**Comment by ctrueden** [comment]
Since we are definitely not planning to reintroduce the Refresh Menus functionality, I am closing with a "won't fix" here. Fortunately, @hinerm [added an informative message](776bc7b5d73b228f15c324f7c6a1cc26def4d20a) when you try to use Refresh Menus explaining that ImageJ should be restarted. So hopefully that is good enough.
